In [1]:
!pip install openpyxl

In [2]:
import numpy as np
import pprint

In [3]:
# function
import numpy as np
import os
import pandas as pd
import openpyxl
from tkinter import filedialog
from tkinter import messagebox

def get_states_list(states_num):
    """states_num 인자에 상태의 갯수를 입력하고, 갯수만큼 상태들을 입력하여 states_list를 반환한다."""
    states_list = []
    text = "Enter the states."
    print(text)
    for i in range(states_num):
        text = str(input())
        states_list.append(text)
    return states_list

def matrix_generator(statesList):
    name_list = []
    for i in range(len(statesList)):
        for j in range(len(statesList)):
            name_list.append(str(i) + str(j))
    return name_list

def check_this_matrix(matrixProbabilityList):
    for i in matrixProbabilityList:
        sum_in_row = 0
        for j in range(len(i)):
            sum_in_row += i[j]
        print("row", i, "is ok") if round(sum_in_row, 2) == 1 else print("Error")

def iteration_transitionMatrix(matrixName,firstState,numberth,iterations):
    iteration_list = []
    for iteration in range(iterations):
        iteration_list.append(matrixName(firstState,numberth))

    return iteration_list

def probability_of_endState(iteration_list,endState,numberth,iterations):
    count = 0
    for smaller_list in iteration_list:
        if(smaller_list[numberth] == endState):
            count += 1
    percentage = (count / iterations) * 100
    return percentage

def probability_States_everystep(iteration_list, statesList, numberth, iterations):
    probabilities = []
    for num in range(numberth):
        count = [0] * len(statesList)
        for state in range(len(statesList)):
            for iteration in range(iterations):
                if iteration_list[iteration][num] == statesList[state]:
                    count[state] += 1
        k = [i * 100 / iterations for i in count]
        probabilities.append(k)

    return np.array(probabilities).reshape(numberth,len(statesList))

def solution(matrixName, power):
    original, result = matrixName, matrixName
    i = 1
    while i != power:
        result = np.dot(matrixName, original).tolist()
        i+=1
    return result

def get_matrix_xlsx(Row, Column):
    file_num, xml_file, file_gbxml, save_path = 0, '', '', ''
    while file_num < 1:
        xlsx_file = filedialog.askopenfilenames(initialdir="/", title="데이터를 읽어올 xlsx 파일을 선택하세요.",
                                                filetypes=(("xlsx files", "*.xlsx"), ("csv files", "*.csv"),
                                                           ("all files", "*.*")))
        if xlsx_file == '':
            messagebox.showwarning("경고!", "파일을 추가 하세요.")
            pass
        else:
            Location = os.path.split(xlsx_file[0])[0]
            File = os.path.split(xlsx_file[0])[1]
            data_pd = pd.read_excel('{}/{}'.format(Location, File), sheet_name = 0,
                                    header = None, names = None, index_col = None)
            data_np = pd.DataFrame.to_numpy(data_pd)
            file_num += 1

            return data_pd, \
                   data_np, data_np[Row][Column]

def export_matrix_csv(matrixName):
    file_num, save_location, save_fileName = 0, '', ''
    while file_num < 1:
        save_location = filedialog.askdirectory(initialdir="/", title="결과를 저장할 경로를 선택하세요.")
        if save_location == '':
            messagebox.showwarning("경고!", "경로를 선택하세요.")
        else:
            print("추출결과를 저장할 파일 이름을 입력하세요.")
            save_fileName = input()
        file_num += 1
    transformToDataFrame = pd.DataFrame(matrixName)
    transformToDataFrame.to_excel(save_location + '/' + str(save_fileName) + '.xlsx', index=False, index_label=False)
    
def contaminantPosition_prediction(first_position,numberth):
    positionList = [first_position]
    i, prob = 0, 1
    present_position = first_position
    #move_path = []

    while i != numberth:
        statesIndex = statesList.index(present_position)

        choice = np.random.choice(matrixNameList[statesIndex], replace = True, p = matrixProbabilityList[statesIndex])
        prob = prob * probabilityDictionary[choice]
        statesIndexColumn = list(matrixNameList[statesIndex]).index(choice)

        present_position = statesList[statesIndexColumn]
        positionList.append(present_position)
        i += 1

    return positionList


In [5]:
statesList = get_states_list(65)

Enter the states.
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64


In [6]:
nameList = matrix_generator(statesList)
nameList

['00',
 '01',
 '02',
 '03',
 '04',
 '05',
 '06',
 '07',
 '08',
 '09',
 '010',
 '011',
 '012',
 '013',
 '014',
 '015',
 '016',
 '017',
 '018',
 '019',
 '020',
 '021',
 '022',
 '023',
 '024',
 '025',
 '026',
 '027',
 '028',
 '029',
 '030',
 '031',
 '032',
 '033',
 '034',
 '035',
 '036',
 '037',
 '038',
 '039',
 '040',
 '041',
 '042',
 '043',
 '044',
 '045',
 '046',
 '047',
 '048',
 '049',
 '050',
 '051',
 '052',
 '053',
 '054',
 '055',
 '056',
 '057',
 '058',
 '059',
 '060',
 '061',
 '062',
 '063',
 '064',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '110',
 '111',
 '112',
 '113',
 '114',
 '115',
 '116',
 '117',
 '118',
 '119',
 '120',
 '121',
 '122',
 '123',
 '124',
 '125',
 '126',
 '127',
 '128',
 '129',
 '130',
 '131',
 '132',
 '133',
 '134',
 '135',
 '136',
 '137',
 '138',
 '139',
 '140',
 '141',
 '142',
 '143',
 '144',
 '145',
 '146',
 '147',
 '148',
 '149',
 '150',
 '151',
 '152',
 '153',
 '154',
 '155',
 '156',
 '157',
 '158',
 '159',
 '160',
 '161',
 '16

In [12]:
matrixProbabilityList = get_matrix_xlsx(64,64)[1]

In [16]:
probabilityList = matrixProbabilityList.reshape(1,65*65)[0]
probabilityDictionary = dict(zip(nameList,probabilityList))
matrixNameList = np.array(nameList).reshape(65, 65)

In [26]:
iteration_list = iteration_transitionMatrix(contaminantPosition_prediction, firstState='36', numberth=50, iterations=100000)

In [27]:
iteration_list

[['36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36'],
 ['36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36'],
 ['36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36',
  '36'

In [28]:
probabilities_result = probability_States_everystep(iteration_list, statesList, numberth=50, iterations=100000)

In [29]:
print('The probabilities:\n', str(probabilities_result)+'%')

The probabilities:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]%


In [30]:
export_matrix_csv(probabilities_result)

추출결과를 저장할 파일 이름을 입력하세요.
test2
